# Docker环境配置
server:
  port: 8085

spring:
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  redis:
    host: zhihealth-redis
    port: 6379

logging:
  level:
    com.zhihealth.cache: info
