server:
  port: 8086

spring:
  application:
    name: zhihealth-alert
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        import-check:
          enabled: false
  config:
    import: optional:nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhihealth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhihealth.alert.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

redis:
  host: localhost
  port: 6379
  password:
  database: 0
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0

logging:
  level:
    com.zhihealth.alert: debug
