CREATE TABLE IF NOT EXISTS `operation_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `operator` varchar(100) DEFAULT NULL COMMENT '操作人',
  `operator_id` varchar(50) DEFAULT NULL COMMENT '操作人ID',
  `module` varchar(50) NOT NULL COMMENT '操作模块（user/device/collect/storage/alert/ai/settings/report）',
  `action_type` varchar(30) NOT NULL COMMENT '操作类型（auth/data/config/alert/ai/file/other）',
  `description` varchar(500) DEFAULT NULL COMMENT '操作描述',
  `method` varchar(255) DEFAULT NULL COMMENT '方法名',
  `url` varchar(500) DEFAULT NULL COMMENT '请求URL',
  `request_method` varchar(10) DEFAULT NULL COMMENT '请求方式（GET/POST/PUT/DELETE）',
  `request_params` text COMMENT '请求参数（JSON格式）',
  `response_data` text COMMENT '响应结果（JSON格式）',
  `ip_address` varchar(50) DEFAULT NULL COMMENT 'IP地址',
  `user_agent` varchar(500) DEFAULT NULL COMMENT '浏览器信息',
  `result` varchar(20) NOT NULL COMMENT '执行结果（success/failed/error）',
  `duration` bigint(20) DEFAULT NULL COMMENT '耗时（毫秒）',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '错误信息',
  `operate_time` datetime NOT NULL COMMENT '操作时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_operator` (`operator`),
  KEY `idx_module` (`module`),
  KEY `idx_action_type` (`action_type`),
  KEY `idx_result` (`result`),
  KEY `idx_operate_time` (`operate_time`),
  KEY `idx_ip_address` (`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统操作日志表';
