CREATE TABLE IF NOT EXISTS `ai_analysis_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `analysis_type` varchar(50) NOT NULL COMMENT '分析类型（health_data_analysis/trend_prediction/anomaly_detection/health_report_generation）',
  `input_data` text COMMENT '输入数据（JSON格式）',
  `result_data` text COMMENT '结果数据（JSON格式）',
  `model_used` varchar(100) DEFAULT NULL COMMENT '使用的模型',
  `confidence_score` double DEFAULT NULL COMMENT '置信度（0-1）',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '状态（0-失败 1-成功）',
  `error_message` varchar(500) DEFAULT NULL COMMENT '错误信息',
  `analysis_time` datetime NOT NULL COMMENT '分析时间',
  `execution_time_ms` bigint(20) DEFAULT NULL COMMENT '执行耗时（毫秒）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_analysis_type` (`analysis_type`),
  KEY `idx_status` (`status`),
  KEY `idx_analysis_time` (`analysis_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI分析记录表';
